spring:
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test-db
    username: test
    password: test@123
  modulith:
    moments:
      enable-time-machine: true
      republish-outstanding-events-on-restart: true
  jpa:
    generate-ddl: true
    open-in-view: false
  threads:
    virtual:
      enabled: true
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog.yaml
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    listener:
      simple:
        default-requeue-rejected: false
logging:
  level:
    org.springframework: info
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
